networks:
  web:
    external: true

services:
    proxy-chat-api:
      env_file:
        - .env
      container_name: "proxy-chat-api"
      volumes:
        - ./app:/app
      build: .
      labels:
        traefik.enable: "true"
        traefik.http.routers.proxy-chat-api.rule: Host(`${API_HOST}`)
        traefik.http.routers.proxy-chat-api.tls: "true"
        traefik.http.routers.proxy-chat-api.entrypoints: https
        traefik.http.routers.proxy-chat-api.tls.certresolver: le
      expose:
        - "8080"
      ports:
        - 8080:8080
      networks:
        - web
